openapi: 3.0.1
info:
  title: 'Motor Insurance Products'
  version: '1.0.0'
  description: 'This specification includes all relevant artefacts for Motor Insurance Products API Specification. In Malaysia, product aggregators have to obtain product information on cards through either web scraping or entering into exclusive arrangement with the financial institutions. Through standardized API, third parties including fintech companies are able to develop solutions which target retail consumers.'
  contact:
    name: 'BNM Open API Team'
    email: 'oapi@bnm.gov.my'
servers:
  - url: 'https://api.sample.com'
    description: 'Production server URL'
  - url: 'https://api.test.sample.com'
    description: 'Staging server URL'
paths:
  /motor:
    get:
      tags:
        - 'Motor Vehicle'
      summary: 'Retrieve the detail of Motor Insurance products'
      description: 'This API endpoint will return all Motor Insurance products offered by the insurance company or takaful operator'
      operationId: getProducts
      security:
          - default: [public]
      responses:
        '200':
          description: 'Successful response'
          content:
            application/json:
              schema:
                title: Sample
                type: object
                properties:
                  meta:
                    type: object
                    required:
                      - issuer_code
                      - last_updated
                      - version
                      - total_result
                    properties:
                      issuer_code:
                        type: string
                        maxLength: 3
                        description: 'ISM code for company code - Table 1'
                      last_updated:
                        type: string
                        format: date-time
                        description: 'Last updated date of product list'
                        example: '2018-09-17T17:30:12.345+08:00'
                      version:
                        type: string
                        description: 'API version'
                        example: '0.1-dev'
                        maxLength: 25
                      total_result:
                        type: integer
                        description: 'Number of products returned'
                        example: 3
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        product_details:
                          type: object
                          required:
                            - name
                            - summary
                            - description
                            - shariah_compliance
                            - vehicle_type
                            - cover_type
                            - min_sum_insured
                            - max_sum_insured
                            - pds_url
                            - tnc_url
                          properties:
                            name:
                              type: string
                              description: 'Product name'
                              maxLength: 150
                              example: 'Motor Comprehensive Insurance'
                            underwriter:
                              type: string
                              maxLength: 150
                              description: 'Underwriter'
                            summary:
                              type: string
                              maxLength: 255
                              description: 'Summary of product description'
                            description:
                              type: string
                              description: 'Product descrption'
                              maxLength: 4000
                            shariah_compliance:
                              type: boolean
                              description: 'The indicator for Islamic or Conventional product'
                              example: true
                            vehicle_type:
                              type: array
                              items:
                                type: string
                                maxLength: 2
                                description: 'ISM code for class of vehicle - Table 5'
                            cover_type:
                              type: string
                              maxLength: 2
                              description: 'ISM code for type of coverage - Table 4'
                            hotline_support:
                              type: object
                              required:
                                - operator
                                - road_assistance
                                - claim_assistance
                                - email
                              properties:
                                operator:
                                  type: number
                                  description: 'Insurance customer service hotline'
                                  example: 1300888080
                                road_assistance:
                                  type: number
                                  description: 'Road side assistance Hotline'
                                  example: 1300888080
                                claim_assistance:
                                  type: number
                                  description: 'Claim assistance hotline'
                                  example: 1300888080
                                24h_assistance:
                                  type: number
                                  description: '24 hours roadside breakdown assistance'
                                  example: 1300888080
                                24h_towing:
                                  type: number
                                  description: '24 hours towing service'
                                  example: 1300888080
                                alternative_travel:
                                  type: number
                                  description: 'Alternative travel assistance'
                                live_chat:
                                  type: string
                                  format: uri
                                  description : 'Absolute URL to 24/7 Live Chat Support'
                                  maxLength: 255
                                email:
                                  type: string
                                  format: email
                                  description: 'Email Address to Support'
                                  maxLength: 150
                            online_purchase:
                              type: object
                              properties:
                                portal_flag:
                                  type: boolean
                                  description: 'Online purchase portal availability'
                                portal_url:
                                  type: string
                                  format: uri
                                  description: 'Absolute URL to online portal link'
                                  maxLength: 255
                                payment_options:
                                  type: array
                                  items:
                                    type: string
                                    enum:
                                      - 'card'
                                      - 'ewallet'
                                      - 'fpx'
                                      - 'online_banking'
                                      - 'reward_point'
                                    description: 'Online purchase payment options'
                                    maxLength: 25
                            min_sum_insured:
                              type: number
                              description: 'Minimum sum insured in MYR'
                              example: 10000
                            max_sum_insured:
                              type: number
                              description: 'Maximum sum insured in MYR'
                              example: 350000
                            epp:
                              type: object
                              properties:
                                bank_name:
                                  type: string
                                  maxLength: 150
                                  description: 'Bank EPP name'
                                issuer:
                                  type: string
                                  maxLength: 150
                                  description: 'Bank of issuance'
                                repayment_period:
                                  type: array
                                  description: 'Repayment period in month'
                                  items:
                                    type: integer
                                    enum:
                                      - 3
                                      - 6
                                      - 9
                                      - 12
                                      - 18
                                      - 24
                                      - 36
                                min_amount:
                                  type: number
                                  description: 'Minimum repayment amount in MYR'
                                max_amount:
                                  type: number
                                  description: 'Maximum repayment amount in MYR'
                            insured_drivers:
                              type: object
                              required:
                                - max_drivers
                                - max_free_drivers
                                - additional_driver_charges
                              properties:
                                max_drivers:
                                  type: integer
                                  description: 'Maximum number of insured drivers'
                                max_free_drivers:
                                  type: integer
                                  description: 'Maximum free insured drivers'
                                additional_driver_charges:
                                  type: integer
                                  description: 'Additional driver charges in MYR'
                            excess:
                              type: object
                              properties:
                                min_claim:
                                  type: number
                                  description: 'Minimum claim excess in MYR'
                                max_claim:
                                  type: number
                                  description: 'Maximum claim excess in MYR'
                                conditions:
                                  required:
                                    - below_age
                                    - unnamed_driver
                                  type: object
                                  properties:
                                    below_age:
                                      type: boolean
                                      description: 'Excess needed for below 21 years old'
                                    license_L:
                                      type: boolean
                                      description: 'Excess needed for L license holder'
                                    license_P:
                                      type: boolean
                                      description: 'Excess needed for P license holder'
                                    unnamed_driver:
                                      type: boolean
                                      description: 'Excess for unnamed driver'
                            no_claim_bonus:
                              type: number
                              description: 'Percentage of discount for no claim bonus'
                              minimum: 0
                              maximum: 100
                            no_claim_bonus_desc:
                              type: string
                              description: 'No claim bonus description'
                              maxLength: 255
                            friend_family_assist:
                              type: boolean
                              description: 'Friends and Family Assistance. For breakdowns, towing, accident etc. When insured friends and family are using Policy Holder vehicle.'
                            towing:
                              type: object
                              required:
                                - free_max_km
                                - extended_coverage
                              properties:
                                free_max_km:
                                  type: integer
                                  description: 'Maximum KM for free towing'
                                max_amount:
                                  type: number
                                  description: 'Maximum amount for free towing in MYR'
                                additional_charges:
                                  type: number
                                  description: 'Additional charges for towing in MYR'
                                additional_charges_notes:
                                  type: string
                                  description: 'Notes for additional charges'
                                  example: 'Charges applied per KM'
                            extended_coverage:
                              type: boolean
                              description: 'Coverage outside of Malaysia'
                            extended_coverage_notes:
                              type: string
                              description: 'Notes for extended coverage'
                              example: 'Standard coverage cover for SG & Brunei. Coverage can be extended to Thailand and Kalimatan with additional premium'
                              maxLength: 255
                            coverage_benefits:
                              type: object
                              properties:
                                coverage_detail:
                                  type: array
                                  items:
                                    type: object
                                    properties:
                                      coverage_type:
                                        type: string
                                        enum:
                                          - 'accidental_death'
                                          - 'bodily_injury'
                                          - 'car_accessories'
                                          - 'compassionate_flood_expense'
                                          - 'damage_of_property'
                                          - 'damage_own_vehicle'
                                          - 'e_hailing'
                                          - 'full_body_spray_painting'
                                          - 'legal_costs'
                                          - 'legal_liability_of_passenger'
                                          - 'legal_liability_to_passenger'
                                          - 'others'
                                          - 'special_perils'
                                          - 'strike_riot_civil_commotion'
                                          - 'warranty_worksmanship'
                                          - 'windscreen'
                                        description: 'Type of coverage or benefits'
                                        maxLength: 50
                                      coverage_type_others:
                                          type: string
                                          maxLength: 50
                                          description: 'Description for coverage type = others'
                                      covered_flag:
                                        type: boolean
                                        description: 'Indicator of coverage being offered'
                                      optional_benefit:
                                        type: boolean
                                        description: 'Indicator of standard or optional benefit'
                                      amount:
                                        type: number
                                        description: 'Maximum coverage amount in MYR'
                                      notes:
                                        type: string
                                        description: 'Additional notes to further describe coverage'
                                        maxLength: 255
                            pds_url:
                              type: string
                              format: uri
                              description: 'Absolute URL for Product Disclosure Sheet'
                              maxLength: 255
                            tnc_url:
                              type: string
                              format: uri
                              description: 'Absolute URL for Terms and Condition'
                              maxLength: 255
          headers:
            Strict-Transport-Security:
              schema:
                type: string
                description: 'HTTPS strict transport security header'
                default: "max-age=31536000; includeSubDomains; preload"
            X-Frame-Options:
              schema:
                type: string
                description: "Prevent this request from being loaded in any iframes"
                default: "DENY"
            X-Content-Type-Options:
              schema:
                type: string
                description: "Prevent content sniffing where no mimetype is sent"
                default: "nosniff"

        default:
          $ref: '#/components/responses/default'

components:
  securitySchemes:
    default:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: /oauth/token
          scopes:
            public: Read-only access to public data
  responses:
    default:
      description: 'Unexpected error'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
  schemas:
    Error:
      type: object
      properties:
        code:
          type: integer
          enum:
            - 400
            - 408
            - 429
            - 500
            - 503
          description: 'Error code as listed in RFC2616 Status Code Definitions'
        message:
          type: string
          maxLength: 100
